In [2]:
#a.Импортируйте библиотеку NumPy.
import numpy    



In [3]:
#b.Создайте массив из 10 нулей
import numpy as np
array=np.zeros(10)
print(np.array( [0]*10 ))

[0 0 0 0 0 0 0 0 0 0]


In [4]:
#c.Создать массив из 10 единиц.
import numpy as np
array=np.zeros(10)
print(np.array( [1]*10 ))

[1 1 1 1 1 1 1 1 1 1]


In [5]:
#d.Создать массив из 10 пятерок.
import numpy as np
array=np.zeros(10)
print(np.array( [5]*10 ))

[5 5 5 5 5 5 5 5 5 5]


In [6]:
#e.Создать массив из целых чисел от 10 до 50.
array=np.arange(10,51,1)
print(array) 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#f.Создать массив из четных чисел от 10 до 50.

In [7]:
#g.Создать матрицу 3х3 с числами от 0 до 8.
b = np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#h.Создать единичную матрицу 3x3.
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#i.Используйте NumPy для генерации случайного числа от 0 до 1.
import random
print(random.uniform(0, 1))

0.6591136296877026


In [10]:
#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения.
rand_num = np.random.normal(0,1,25)
print(rand_num)

[ 2.01263251 -0.68053254  1.06801063 -0.31835172  0.71084776 -1.27698177
  1.51169944 -0.53420096 -2.30507234  0.36509475 -0.26580102 -1.62772786
  0.11434056  1.34686544  1.49664703  0.28482789 -0.54477634 -2.3235678
  1.20394687  0.32513658  2.50134867  1.63730404  1.20531973  0.08444993
  0.27878768]


In [11]:
#k.Создайте следующую матрицу используя функции библиотеки NumPy:.
a = np.arange(0.01, 1, 0.01)
print(a)

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99]


In [34]:
#l.Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). 
#Эта матрица будет использоваться в последующих задачах
# это наша стартовая матрица 
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [35]:
# Необходимо написать код который вернет следующую матрицу из стартовой:
m=np.array(mat)
print(m[2:,1:])


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [36]:
#m.Написать код обращения к элементу который вернет значение  20 из стартовой матрицы задачи l
print(m[3,4])

20


In [42]:
#n.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
print(m[0:3,1])

[ 2  7 12]


In [43]:
#o.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
print(m[4:])

[[21 22 23 24 25]]


In [44]:
#p.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
print(m[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#q.Получить сумму всех значений в стартовой матрице mat
b = np.sum(mat) 
print(b)


325


In [ ]:
#r.Получить стандартное отклонение в стартовой матрице mat
sd = np.std(mat)
print(sd)


7.211102550927978


In [46]:
#s.Получить сумму значений в колонках в стартовой матрице mat
m.sum(axis=0)

array([55, 60, 65, 70, 75])